name: build

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number ||  github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' && !startsWith(github.ref_name, 'maint/') && github.event_name == 'push' }}

permissions:
  contents: read

env:
  DRY_RUN: ${{ github.ref_name != github.event.repository.default_branch && !startsWith(github.ref_name, 'maint/') }}

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: 📥 Setup Node.js
        uses: ./.github/actions/setup-node

      - name: lint
        run: |
          pnpm eslint -f gha
          pnpm prettier
          pnpm lint:types

  release:
    needs:
      - lint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      # full checkout for semantic-release
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          show-progress: false
          filter: blob:none # we don't need all blobs

      - uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0

      - name: 📥 Setup Node.js
        uses: ./.github/actions/setup-node

      - name: semantic-release
        if: github.event_name == 'push'
        run: pnpm semantic-release --dry-run true --ci ${{env.DRY_RUN != 'true'}} # TODO use ${{env.DRY_RUN}} for dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
